/**
 * database.types.ts — Panoramex CRM
 *
 * This file is auto-generated by the Supabase CLI and should NOT be edited manually.
 * After running `supabase gen types typescript --project-id <id> > src/lib/database.types.ts`,
 * replace this stub with the generated output.
 *
 * To generate:
 *   npx supabase gen types typescript --project-id YOUR_PROJECT_ID --schema public > src/lib/database.types.ts
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      tours: {
        Row: {
          id: string
          name: string
          slug: string
          description: string | null
          inclusions: string[] | null
          image_url: string | null
          min_capacity_alert: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          description?: string | null
          inclusions?: string[] | null
          image_url?: string | null
          min_capacity_alert?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          description?: string | null
          inclusions?: string[] | null
          image_url?: string | null
          min_capacity_alert?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      tour_variants: {
        Row: {
          id: string
          tour_id: string
          name: string
          price_per_person: number
          capacity: number
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tour_id: string
          name: string
          price_per_person: number
          capacity: number
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tour_id?: string
          name?: string
          price_per_person?: number
          capacity?: number
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
      }
      reservations: {
        Row: {
          id: string
          prospect_id: string
          tour_variant_id: string
          service_date: string
          num_people: number
          total_amount: number
          deposit_amount: number
          balance_due: number | null
          status: 'pending' | 'confirmed' | 'cancelled'
          notes: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          prospect_id: string
          tour_variant_id: string
          service_date: string
          num_people: number
          total_amount: number
          deposit_amount?: number
          balance_due?: number | null
          status?: 'pending' | 'confirmed' | 'cancelled'
          notes?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          prospect_id?: string
          tour_variant_id?: string
          service_date?: string
          num_people?: number
          total_amount?: number
          deposit_amount?: number
          balance_due?: number | null
          status?: 'pending' | 'confirmed' | 'cancelled'
          notes?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      reservation_passengers: {
        Row: {
          id: string
          reservation_id: string
          full_name: string
          sort_order: number
        }
        Insert: {
          id?: string
          reservation_id: string
          full_name: string
          sort_order?: number
        }
        Update: {
          id?: string
          reservation_id?: string
          full_name?: string
          sort_order?: number
        }
      }
      agents: {
        Row: {
          id: string
          email: string
          full_name: string
          role: 'admin' | 'agent'
          can_edit_catalog: boolean
          created_at: string
        }
        Insert: {
          id: string
          email: string
          full_name: string
          role?: 'admin' | 'agent'
          can_edit_catalog?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string
          role?: 'admin' | 'agent'
          can_edit_catalog?: boolean
          created_at?: string
        }
      }
      org_settings: {
        Row: {
          id: number
          system_status: 'active' | 'paused'
          message_limit: number
          messages_used: number
          updated_at: string
        }
        Insert: {
          id?: number
          system_status?: 'active' | 'paused'
          message_limit?: number
          messages_used?: number
          updated_at?: string
        }
        Update: {
          id?: number
          system_status?: 'active' | 'paused'
          message_limit?: number
          messages_used?: number
          updated_at?: string
        }
      }
      audit_log: {
        Row: {
          id: string
          actor_id: string
          action: string
          entity_type: string
          entity_id: string
          metadata: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          actor_id: string
          action: string
          entity_type: string
          entity_id: string
          metadata?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          actor_id?: string
          action?: string
          entity_type?: string
          entity_id?: string
          metadata?: Json | null
          created_at?: string
        }
      }
      prospects: {
        Row: {
          id: string
          name: string
          phone: string
          assigned_to: string | null
          status: string
          origin_channel: string | null
          tour_of_interest: string | null
          desired_date: string | null
          num_people: number | null
          tags: string[] | null
          last_activity_at: string | null
          whatsapp_number: string | null
          birth_date: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          phone: string
          assigned_to?: string | null
          status?: string
          origin_channel?: string | null
          tour_of_interest?: string | null
          desired_date?: string | null
          num_people?: number | null
          tags?: string[] | null
          last_activity_at?: string | null
          whatsapp_number?: string | null
          birth_date?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          phone?: string
          assigned_to?: string | null
          status?: string
          origin_channel?: string | null
          tour_of_interest?: string | null
          desired_date?: string | null
          num_people?: number | null
          tags?: string[] | null
          last_activity_at?: string | null
          whatsapp_number?: string | null
          birth_date?: string | null
          created_at?: string
        }
      }
      interactions_timeline: {
        Row: {
          id: string
          prospect_id: string
          agent_id: string | null
          interaction_type: string
          content: string
          metadata: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          prospect_id: string
          agent_id?: string | null
          interaction_type: string
          content: string
          metadata?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          prospect_id?: string
          agent_id?: string | null
          interaction_type?: string
          content?: string
          metadata?: Json | null
          created_at?: string
        }
      }
      webhook_events: {
        Row: {
          id: string
          payload: Json
          status: string
          error: string | null
          created_at: string
          updated_at: string | null
        }
        Insert: {
          id?: string
          payload: Json
          status?: string
          error?: string | null
          created_at?: string
          updated_at?: string | null
        }
        Update: {
          id?: string
          payload?: Json
          status?: string
          error?: string | null
          created_at?: string
          updated_at?: string | null
        }
      }
      conversations: {
        Row: {
          id: string
          prospect_id: string
          bot_status: string
          current_flow: string | null
          flow_state: Json | null
          last_activity_at: string
        }
        Insert: {
          id?: string
          prospect_id: string
          bot_status?: string
          current_flow?: string | null
          flow_state?: Json | null
          last_activity_at?: string
        }
        Update: {
          id?: string
          prospect_id?: string
          bot_status?: string
          current_flow?: string | null
          flow_state?: Json | null
          last_activity_at?: string
        }
      }
      messages: {
        Row: {
          id: string
          conversation_id: string
          sender_type: string
          agent_id: string | null
          content: string | null
          media_url: string | null
          media_type: string | null
          meta_message_id: string | null
          send_status: string
          retry_count: number
          next_retry_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          conversation_id: string
          sender_type: string
          agent_id?: string | null
          content?: string | null
          media_url?: string | null
          media_type?: string | null
          meta_message_id?: string | null
          send_status?: string
          retry_count?: number
          next_retry_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          conversation_id?: string
          sender_type?: string
          agent_id?: string | null
          content?: string | null
          media_url?: string | null
          media_type?: string | null
          meta_message_id?: string | null
          send_status?: string
          retry_count?: number
          next_retry_at?: string | null
          created_at?: string
        }
      }
      campaigns: {
        Row: {
          id: string
          name: string
          type: string
          template_name: string
          status: string
          target_filters: Json | null
          created_at: string
          created_by: string
        }
        Insert: {
          id?: string
          name: string
          type: string
          template_name: string
          status?: string
          target_filters?: Json | null
          created_at?: string
          created_by: string
        }
        Update: {
          id?: string
          name?: string
          type?: string
          template_name?: string
          status?: string
          target_filters?: Json | null
          created_at?: string
          created_by?: string
        }
      }
      campaign_sends: {
        Row: {
          id: string
          campaign_id: string
          prospect_id: string | null
          phone_number: string
          status: string
          meta_message_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          campaign_id: string
          prospect_id?: string | null
          phone_number: string
          status?: string
          meta_message_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          campaign_id?: string
          prospect_id?: string | null
          phone_number?: string
          status?: string
          meta_message_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      satisfaction_surveys: {
        Row: {
          id: string
          reservation_id: string
          prospect_id: string
          rating: number
          feedback: string | null
          created_at: string
        }
        Insert: {
          id?: string
          reservation_id: string
          prospect_id: string
          rating: number
          feedback?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          reservation_id?: string
          prospect_id?: string
          rating?: number
          feedback?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      tour_availability_view: {
        Row: {
          variant_id: string
          tour_id: string
          variant_name: string
          capacity: number
          service_date: string
          reserved_seats: number
          available_seats: number
          min_capacity_alert: number
          availability_status: 'available' | 'low_availability' | 'sold_out'
        }
      }
    }
    Functions: {
      get_current_agent_role: {
        Args: Record<string, never>
        Returns: string
      }
    }
    Enums: Record<string, never>
  }
}
